GET http://localhost:3333/
###
GET http://localhost:3333/api/v1/fornecedores
###
GET http://localhost:3333/api/v1/fornecedores/678bdd79d19da53641876baa
###
POST http://localhost:3333/api/v1/fornecedores
Content-Type: application/json

{
    "nome": "Gransyste",
    "cnpj": "10641901000119",
    "telefone": "84 9870-4050",
    "email": "azevedogustavo@campos.br",
    "endereco": "Colônia da Cunha, 944, Lima, Pernambuco",
    "status": "inativo",
    "privado": true
}
###
PATCH http://localhost:3333/api/v1/fornecedores/6789ace400935dfba939e4e2
Content-Type: application/json

{
    "status": "ativo"
}
###
DELETE http://localhost:3333/api/v1/fornecedores/678bdd79d19da53641876baa
###
GET http://localhost:3333/api/v1/fornecedores?sort=nome
###
GET http://localhost:3333/api/v1/fornecedores?fields=produtos,nome
###